# Generated by Django 2.0 on 2018-04-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NA', max_length=50)),
                ('course', models.CharField(default='NA', max_length=10)),
                ('email', models.EmailField(default='NA', max_length=254)),
                ('suggestion', models.TextField(default='NA', max_length=1000)),
            ],
        ),
    ]
