# Generated by Django 2.0 on 2018-04-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farewell', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='suggestion',
            new_name='text',
        ),
    ]
